from __future__ import annotations

from pathlib import Path

import pandas as pd


def _markdown_table(df: pd.DataFrame, max_rows: int = 8) -> str:
    if df.empty:
        return "_No data._"
    small = df.head(max_rows).copy()
    headers = [str(col) for col in small.columns]
    rows = []
    rows.append("| " + " | ".join(headers) + " |")
    rows.append("| " + " | ".join("---" for _ in headers) + " |")
    for _, row in small.iterrows():
        values = [str(row[col]).replace("|", "/") for col in small.columns]
        rows.append("| " + " | ".join(values) + " |")
    return "\n".join(rows)


def write_report(results: dict, insights: list[str], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    kpis = results["kpis"]
    monthly = results["monthly"]
    category = results["category"]
    channel = results["channel"]
    inventory = results["inventory_risk"]
    review_summary = results["review_summary"]

    insight_text = "\n".join(f"- {item}" for item in insights)
    content = f"""# Enterprise Business Analysis Report

## 1. Business Context

This report is generated by `YRH Enterprise Data Agent`. The demo case simulates a small Chinese retail/e-commerce company and analyzes orders, products, users, channels, inventory, marketing, and reviews.

## 2. Core KPIs

| Metric | Value |
| --- | ---: |
| GMV | {kpis['gmv']:,.2f} |
| Net sales | {kpis['net_sales']:,.2f} |
| Orders | {kpis['orders']:,} |
| Active users | {kpis['active_users']:,} |
| Average order value | {kpis['avg_order_value']:,.2f} |
| Refund rate | {kpis['refund_rate']:.2%} |
| Gross margin | {kpis['gross_margin']:.2%} |

## 3. Key Findings

{insight_text}

## 4. Monthly Sales

{_markdown_table(monthly)}

## 5. Category Analysis

{_markdown_table(category)}

## 6. Channel Analysis

{_markdown_table(channel)}

## 7. Inventory Risk

{_markdown_table(inventory[inventory.get('stock_status', 'normal') != 'normal'] if not inventory.empty else inventory)}

## 8. Review Summary

{_markdown_table(review_summary)}

## 9. Business Actions

- Protect the top category and monitor stock shortage for high-selling products.
- Compare channel ROI before increasing marketing spend.
- Build a user operation list from the `core` user segment.
- Review low-rating comments and convert them into product or service improvement tasks.

## 10. Next Analysis Questions

- Which products drive both high revenue and high gross margin?
- Which channels attract users with better repeat purchase behavior?
- Which inventory risks will affect the next 30 days of sales?
- Which review keywords are most related to refund risk?
"""
    output_path.write_text(content, encoding="utf-8")


def write_profile_report(table_summary: pd.DataFrame, field_profile: pd.DataFrame, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = f"""# Data Quality Report

## Table Summary

{_markdown_table(table_summary, max_rows=20)}

## Field Profile

{_markdown_table(field_profile, max_rows=80)}
"""
    output_path.write_text(content, encoding="utf-8")
